### ISSUE TITLE
UI: Add "League Details" Tab

### ISSUE THREAD

**Issue by Alesvoy** [masiddee/nextjs-soccer-manager#7]
# Description
Create tabbing component

#ToDo:
- [x] Install react-tabs package to handle tabbing functionality
- [x] Add tab 1 and placeholder tabs for the remaining 2 tabs (to be added in a different ticket)
- [x] Tab 1 should display the following league details received from the API: league start date and end date, game dates and game times (in a comma separate list), sign up deadline date, and the league description

# Things to keep in mind
* Inside the game schedule it can be good to add a calendar, this will help the user have a better experience using this league manager
